---

# Install Sensu Client

- hosts: clients
  remote_user: sayers
  sudo: yes
  roles:
    - role: sensu_clients
      plugins_ref:
	    DEVU0000908: "{{ base }}"
	    DEVU0000900: "{{ base }}"
	    DEVU0001026: "{{ base }}"
	    DEVU0001027: "{{ base }}"
      subscriptions_ref:
  	    DEVU0000908:
	      - base
	    DEVU0000900: 
	      - base
	    DEVU0001026:
	      - base
	    DEVU0001027:
	      - base
