---

#####################################
# Installing Sensu via repositories #
#####################################

- name: Installing Sensu Dependency Packages via repository
  package:
    name: libselinux-python
    state: present
  when: libselinux_python_package_path == ''

- name: Adding Sensu Repository (RedHat)
  copy:
    src: "../files/sensu.repo"
    dest: "/etc/yum.repos.d/sensu.repo"
  when: (sensu_package_path == '' and ansible_os_family == "RedHat")

- name: Adding Sensu Repository (Debian)
  copy:
    src: "../files/sensu.list"
    dest: "/etc/apt/sources.list.d/sensu.list"
  when: (sensu_package_path == '' and ansible_os_family == "Debian")

- name: Installing Sensu via public repository
  package:
    name: sensu
    state: present
  when: sensu_package_path == ''

#####################################
# Installing Sensu via package URL  #
#####################################

- name: Installing Sensu Dependency Packages (via package URL)
  package:
    name: "{{ libselinux_python_package_path }}"
    state: present
  when: not libselinux_python_package_path == ''

- name: Installing Sensu (via package URL)
  package:
    name: "{{ sensu_package_path }}"
    state: present
  when: not sensu_package_path == ''
