---

- name: Installing Sensu Dependency Packages via public repository
  package:
    name: libselinux-python
    state: present
  when: package.use_url|bool == false

- name: Adding Sensu Repository (RedHat)
  copy:
    src: "../files/sensu.repo"
    dest: "/etc/yum.repos.d/sensu.repo"
  when: (package.use_url|bool == false and ansible_os_family == "RedHat")

- name: Adding Sensu Repository (Debian)
  copy:
    src: "../files/sensu.list"
    dest: "/etc/apt/sources.list.d/sensu.list"
  when: (package.use_url|bool == false and ansible_os_family == "Debian")

- name: Installing Sensu via public repository
  package:
    name: sensu
    state: present
  when: package.use_url|bool == false

- name: Installing Sensu (via package URL)
  package:
    name: "{{ package.url }}"
    state: present
  when: package.use_url|bool == true