---

- name: Installing Sensu
  yum:
    name: "{{ rpm_repo }}/{{ sensu.name }}/{{ sensu.version }}/{{ sensu.name }}-{{ sensu.version }}.rpm"
    state: present
  when: specify_rpm_repo|bool == true


- name: Preparing Sensu Install
  package:
    name: libselinux-python
    state: present
  when: specify_rpm_repo|bool == false


- name: Add Sensu repo (RedHat)
  copy:
    src: "../files/sensu.repo"
    dest: "/etc/yum.repos.d/sensu.repo"
  when: (specify_rpm_repo|bool == false and ansible_os_family == "RedHat")

- name: Add Sensu repo (Debian) - GPG Public Key
  copy:
    src: "../files/sensu.list"
    dest: "/etc/apt/sources.list.d/sensu.list"
  when: (specify_rpm_repo|bool == false and ansible_os_family == "Debian")


- name: Installing Sensu
  package:
    name: sensu
    state: present
  when: specify_rpm_repo|bool == false