---

- include_vars: prerequisites_plugins.yml

- name: Copying configuration files onto remote machine
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ local_files }}"

- name: Pulling down Sensu installation files ({{ sensu_rpm.name }}-{{ sensu_rpm.version }}.rpm)
  get_url:
    url: "{{ rpm_repo }}/{{ sensu_rpm.name }}/{{ sensu_rpm.version }}/{{ sensu_rpm.name }}-{{ sensu_rpm.version }}.rpm"
    dest: "/tmp/"

- name: Installing Sensu
  yum:
    name: "/tmp/{{ sensu_rpm.name }}-{{ sensu_rpm.version }}.rpm"
    state: present

##############################
 
- name: Installing Plugins
  gem:
    name: "{{ item }}"
    executable: /opt/sensu/embedded/bin/gem
    repository: "{{ gem_repo }}"
  with_items: "{{ plugin_dict[ansible_hostname] }}"




