---

- name: Copying prequisite files to remote machine
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: "../artifacts/{{ sensu_rpm }}", dest: "/tmp/{{ sensu_rpm }}" } 
    - { src: "../artifacts/ssl/", dest: "/etc/sensu/ssl" }
    - { src: "../artifacts/plugins/", dest: "/tmp/plugins" }
    - { src: "../artifacts/conf.d/", dest: "/etc/sensu/conf.d" }

- name: Installing components
  yum:
    name: "/tmp/{{ sensu_rpm }}"
    state: present

- name: Installing plugins
  gem:
    name: "{{ item.name }}"
    executable: /opt/sensu/embedded/bin/gem
    gem_source: "/tmp/plugins/{{ item.name }}{{ item.suffix }}"
  with_items:
    - { name: 'sys-filesystem', suffix: '-1.1.5.gem'}
    - { name: 'chronic_duration', suffix: '-0.10.6.gem'}
    - { name: 'sensu-plugin', suffix: '-1.4.2.gem'}
    - { name: 'sensu-plugins-disk-checks', suffix: '-2.0.1.gem'}
    - { name: 'sensu-plugins-load-checks', suffix: '-1.0.0.gem'}
    - { name: 'sensu-plugins-memory-checks', suffix: '-1.0.2.gem'}
    - { name: 'sensu-plugins-jenkins', suffix: '-0.1.0.gem'}


