---

- name: Installing Sensu
  yum:
    name: "{{ rpm_repo }}/{{ sensu.name }}/{{ sensu.version }}/{{ sensu.name }}-{{ sensu.version }}.rpm"
    state: present
  when: specify_nexus_repo|bool == true

- name: Installing Sensu
  yum:
    name: sensu
    state: present
  when: specify_nexus_repo|bool == false