---

- name: Copying configuration files onto remote machine
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "../files/ssl/cert.pem", dest: "/etc/sensu/ssl/" }
    - { src: "../files/ssl/key.pem", dest: "/etc/sensu/ssl/" }
  when: rabbitmq_use_ssl|bool == true

- name: Configure RabbitMQ
  template:
    src: rabbitmq.json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
    owner: root
    group: root
    mode: 0755
